/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef OUYAFACE_AUTODEFS_H
#define OUYAFACE_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_OUYAFACE_NAME "ouyaFace"
#define S3E_EXT_OUYAFACE_HASH 0x3bf17132

#endif /* !OUYAFACE_AUTODEFS_H */
