/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "ouyaFace_autodefs.h"
#include "s3eEdk.h"
#include "ouyaFace.h"
//Declarations of Init and Term functions
extern s3eResult ouyaFaceInit();
extern void ouyaFaceTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static void ouyaInit_wrap(const char* pDeveloperId, const char* pApplicationKey)
{
    IwTrace(OUYAFACE_VERBOSE, ("calling ouyaFace func on main thread: ouyaInit"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ouyaInit, 2, pDeveloperId, pApplicationKey);
}

static void ouyaTerm_wrap()
{
    IwTrace(OUYAFACE_VERBOSE, ("calling ouyaFace func on main thread: ouyaTerm"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ouyaTerm, 0);
}

#define ouyaInit ouyaInit_wrap
#define ouyaTerm ouyaTerm_wrap

#endif

void ouyaFaceRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[15];
    funcPtrs[0] = (void*)ouyaInit;
    funcPtrs[1] = (void*)ouyaTerm;
    funcPtrs[2] = (void*)ouyaFacadeIsInitialised;
    funcPtrs[3] = (void*)ouyaFacadeIsRunningOnOUYAHardware;
    funcPtrs[4] = (void*)ouyaFacadeGetGameData;
    funcPtrs[5] = (void*)ouyaFacadePutGameData;
    funcPtrs[6] = (void*)ouyaFacadeSetTestMode;
    funcPtrs[7] = (void*)ouyaFacadeRequestGamerUUID;
    funcPtrs[8] = (void*)ouyaFacadeRequestReceipts;
    funcPtrs[9] = (void*)ouyaFacadeRequestProductList;
    funcPtrs[10] = (void*)ouyaFacadeRequestPurchase;
    funcPtrs[11] = (void*)ouyaControllerRegister;
    funcPtrs[12] = (void*)ouyaControllerUnRegister;
    funcPtrs[13] = (void*)ouyaControllerGetButtonState;
    funcPtrs[14] = (void*)ouyaControllerGetAxis;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[15] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("ouyaFace", funcPtrs, sizeof(funcPtrs), flags, ouyaFaceInit, ouyaFaceTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int ouyaFaceStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&ouyaFaceRegisterExt;
    return 0;
}

int g_ouyaFaceVal = ouyaFaceStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    ouyaFaceRegisterExt();
}
#endif

#endif
